#!/usr/bin/env python3
"""structural_shuffle_audit.py — perplexity shift under sentence/word shuffling.

A Surface-5 discrimination-evidence capability that probes how much a text's
predictability depends on the *ordering* of its parts. Following the
Luminol-AIDetect method (arXiv:2604.25860, 2026 — **PROVISIONAL / UNVERIFIED
preprint**; see the prior-art fallback below), it scores three variants of a
window under a single causal LM:

  * ``ppl_orig`` — the text at its natural ordering,
  * ``ppl_sent`` — the same text with its sentences randomly permuted,
  * ``ppl_word`` — the same text with all its words randomly permuted,

and reports 5 scalar features describing the perplexity *jump* under shuffling.

The hypothesis (the paper's, the SETEC experiment confirms it empirically):
human prose draws meaning from syntactic and narrative flow, so permuting it
spikes perplexity; AI prose generated by next-token prediction has shallower
inter-sentence dependencies, so shuffling hurts it less *relative to itself* —
a smaller jump. The signal is therefore a **structural, order-dependence
axis**, orthogonal in mechanism to the natural-ordering probability family
(Binoculars cross-perplexity ratio, Fast-DetectGPT curvature, DivEye surprisal
moments), and generator-agnostic by construction.

Implements ``specs/32-structural-shuffle-perplexity.md`` (M1: model-free
orchestration). The model load is the M2 seam; M1 is CPU-only and CI-testable
against an injected (stub) backend.

Posture (no-verdict / anti-Goodhart)
------------------------------------
Ships ``status: heuristic`` with NO threshold and NO verdict band — it reports
a measurement, never an is_ai/is_human label. The 5 features are descriptive
evidence under one scorer model; any AI-likely / human-likely call needs
operator-supplied thresholds applied downstream. This audit is a COMPARISON /
HEURISTIC signal and must NEVER be the held-out SETEC fitness / validation
target (the anti-Goodhart separation is load-bearing). ``test_separation_guard``
and ``test_orthogonal_to_binoculars`` pin the import boundary.

Sign / direction
----------------
Higher ``ppl_diff`` / ``ppl_ratio`` / ``ppl_log_ratio`` / ``ppl_pct_change`` =
a larger perplexity jump under shuffling = **more order-dependent = more
human-like** (the hypothesis direction). Silent sign inversion is the
perturbation family's shared failure mode, so the direction is pinned by
``test_feature_direction_sign``. The direction is a hypothesis, NOT a verdict,
and the score ships uncalibrated.

Prior-art fallback
------------------
The shuffle-perplexity idea is not unique to Luminol. The perturbation-based
detection paradigm is established: DetectGPT (Mitchell et al. 2023,
arXiv:2301.11305) perturbs the *lexical* surface and measures the log-prob
curvature drop; this audit extends the same perturb-and-rescore paradigm to
*order* perturbation. If arXiv 2604.25860 turns out not to exist or to differ,
the method stands as an independent reimplementation of an order-perturbation
probe in the DetectGPT family — no paper-specific number is asserted in this
code.

CLI
---
    python3 plugins/setec-voiceprint/scripts/structural_shuffle_audit.py TARGET \\
        [--scorer gpt_neo_2_7b] [--seed INT] \\
        [--surprisal-dtype auto|fp32|fp16|bf16] [--device DEVICE] \\
        [--json] [--out PATH] [--out-md PATH]
"""

from __future__ import annotations

import argparse
import json
import math
import random
import re
import sys
from pathlib import Path
from typing import Any, Protocol

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from claim_license import ClaimLicense  # type: ignore
from output_schema import build_output  # type: ignore

SCRIPT_VERSION = "0.1.0"
# NEW sibling Surface-5 task surface. Registered as a drop-in fragment in
# claim_license_surfaces/discrimination_structural_shuffle.txt (the single
# source of truth for VALID_TASK_SURFACES + TASK_SURFACE_LABELS), NOT by
# editing a shared dict — so parallel audit PRs don't collide.
TASK_SURFACE = "discrimination_structural_shuffle"
TOOL_NAME = "structural_shuffle_audit"
SCORE_VERSION = "structural_shuffle_v1"

DEFAULT_SEED = 0
# The M2 scorer per the ROADMAP. NOT yet in surprisal_backend.MODEL_ALIASES —
# it is added at M0/M2 behind the CPU-first verification gate. M1 ships against
# an injected stub backend and never loads a model, so the default below is a
# label only (the CLI's model path is the M2 seam).
DEFAULT_SCORER = "gpt_neo_2_7b"
# Below this many words the perplexity estimate (and so the shuffle delta) is
# too noisy to be stable; mirrors the surprisal-tier length floor.
MIN_STABLE_WORDS = 50


DEFAULT_LICENSES = (
    "Reports the perplexity shift of the target text under sentence-level and "
    "word-level shuffling, scored by a single causal LM (scorer model M): the "
    "original perplexity (ppl_orig), the sentence-shuffled and word-shuffled "
    "perplexities (ppl_sent, ppl_word), and 5 derived features describing the "
    "jump (ppl_sum, ppl_diff, ppl_ratio, ppl_log_ratio, ppl_pct_change). A "
    "higher jump means the text's predictability depends MORE on the ordering "
    "of its parts — a candidate (heuristic) signal for human authorship, since "
    "human prose draws meaning from syntactic and narrative flow. This is a "
    "structural, order-dependence measurement under model M; it is a value, "
    "NOT a verdict. The probe is mechanically orthogonal to Binoculars' "
    "cross-perplexity ratio, Fast-DetectGPT's curvature, and DivEye surprisal "
    "moments (those score the natural ordering; this scores permuted variants)."
)

DEFAULT_DOES_NOT_LICENSE = (
    "Does not license a binary AI/human authorship verdict. The shuffle delta "
    "is one heuristic measurement under one model; operator judgment remains "
    "the load-bearing decision step. Ships WITHOUT a framework-calibrated "
    "threshold by default: there is no shipped operating point, so the audit "
    "reports the features only and emits no verdict band. Any AI-likely / "
    "human-likely label requires operator-supplied thresholds calibrated for "
    "this model, corpus, and register, applied downstream. Register caveat: "
    "the upstream near-zero false-positive-rate claim is on academic-news / "
    "general text and is UNVERIFIED; literary-fiction (high human burstiness, "
    "long deliberate sentences) calibration is an EMPIRICAL question, not "
    "assumed — the paper's news-domain 0.001 FPR is NOT carried as fact. "
    "ESL / non-native-English failure mode: text written by non-native English "
    "speakers with non-idiomatic, less order-dependent sentence structure may "
    "show a small perplexity delta and FALSELY resemble the AI profile (the "
    "same Achilles heel as GECScore) — do not apply this signal to ESL / "
    "non-native authorship judgements. Does not control for memorization "
    "(text in the model's training set biases the perplexities). Does not "
    "substitute for Binoculars, Fast-DetectGPT, DivEye, stylometric, or "
    "embedding audits — it complements them as an additional orthogonal axis."
)


_WORD_RE = re.compile(r"[A-Za-z']+")
# Regex sentence-boundary fallback when spaCy is unavailable: split after a
# sentence-final punctuation mark followed by whitespace.
_SENT_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")


def count_words(text: str) -> int:
    return len(_WORD_RE.findall(text.lower()))


# =====================================================================
# Sentence splitting + shuffles (pure Python — no model, no torch)
# =====================================================================


def split_sentences(text: str) -> list[str]:
    """Split ``text`` into sentences.

    Uses spaCy ``en_core_web_sm`` if available (more robust on dialogue-heavy
    literary prose), else a regex fallback that splits after sentence-final
    punctuation. Returns a list of non-empty, stripped sentence strings. The
    fallback is fully stdlib and is what runs in CI.
    """
    stripped = text.strip()
    if not stripped:
        return []
    try:  # pragma: no cover - spaCy path is exercised only when installed
        import spacy  # type: ignore

        # Load a blank English pipeline with just the rule-based sentencizer
        # (no model download needed); falls through to regex on any failure.
        nlp = spacy.blank("en")
        nlp.add_pipe("sentencizer")
        doc = nlp(stripped)
        sents = [s.text.strip() for s in doc.sents if s.text.strip()]
        if sents:
            return sents
    except Exception:
        pass
    parts = _SENT_SPLIT_RE.split(stripped)
    return [p.strip() for p in parts if p.strip()]


def shuffle_sentences(sentences: list[str], seed: int) -> str:
    """Return a single string with the sentences randomly permuted (seeded).

    Deterministic for a given ``seed``. Joining is by a single space; the
    permutation preserves every sentence verbatim (no words added or dropped),
    which ``test_shuffle_sentences_same_words`` pins.
    """
    order = list(sentences)
    random.Random(seed).shuffle(order)
    return " ".join(order)


def shuffle_words(text: str, seed: int) -> str:
    """Return a single string with all whitespace-split tokens randomly
    permuted across the whole passage (seeded).

    Scope (REVIEW Rec-1 / Open Question #4 resolved): this is a SINGLE
    passage-level permutation of every whitespace token — words DO cross
    sentence boundaries. This is the maximal-destruction word-order probe; it
    is distinct from a per-sentence-independent shuffle (which would keep
    sentence membership intact). The passage-level choice is recorded here so
    the scope is explicit rather than inferred. Deterministic for a given
    ``seed``; preserves the exact token multiset.
    """
    tokens = text.split()
    random.Random(seed).shuffle(tokens)
    return " ".join(tokens)


# =====================================================================
# Feature extraction (pure arithmetic — the 5 Luminol features)
# =====================================================================


def extract_shuffle_features(
    ppl_orig: float, ppl_sent: float, ppl_word: float,
) -> dict[str, float]:
    """Compute the 5 shuffle-perplexity features from the perplexity triple.

        ppl_sum        = ppl_sent + ppl_word
        ppl_diff       = (ppl_sent + ppl_word) / 2 - ppl_orig      # signed
        ppl_ratio      = ((ppl_sent + ppl_word) / 2) / ppl_orig
        ppl_log_ratio  = log(ppl_ratio)
        ppl_pct_change = (ppl_ratio - 1) * 100

    Direction: higher ppl_diff / ppl_ratio / ppl_log_ratio / ppl_pct_change =
    a larger jump under shuffling = more order-dependent = more human-like (the
    hypothesis direction; pinned by ``test_feature_direction_sign``). NOT a
    verdict — the score ships uncalibrated.

    Math/bounds guards:
      * ppl_orig <= 0 (rank-0 / empty / degenerate input → perplexity floors at
        ~1.0 for a real model, but a stub or empty input can pass 0) makes the
        ratio undefined: ppl_ratio / ppl_log_ratio / ppl_pct_change are set to
        None rather than dividing by zero or taking log(<=0). ppl_diff and
        ppl_sum stay defined (they need no division).
      * ppl_ratio <= 0 (only possible if a shuffled perplexity is 0, i.e. a
        degenerate average) makes the log undefined → ppl_log_ratio is None.
    """
    avg_shuffled = (ppl_sent + ppl_word) / 2.0
    features: dict[str, Any] = {
        "ppl_sum": ppl_sent + ppl_word,
        "ppl_diff": avg_shuffled - ppl_orig,
    }
    if ppl_orig > 0.0:
        ratio = avg_shuffled / ppl_orig
        features["ppl_ratio"] = ratio
        features["ppl_log_ratio"] = math.log(ratio) if ratio > 0.0 else None
        features["ppl_pct_change"] = (ratio - 1.0) * 100.0
    else:
        # ppl_orig is non-positive: the relative-lift features are undefined.
        # Surface None (an honest "not computable"), never a fabricated 0.0 or
        # 1.0 that would read as "no lift".
        features["ppl_ratio"] = None
        features["ppl_log_ratio"] = None
        features["ppl_pct_change"] = None
    return features


# =====================================================================
# Backend protocol + perplexity helper
# =====================================================================


class _ScorerBackend(Protocol):
    """The audit-facing surface of the scorer. The real
    ``surprisal_backend.SurprisalBackend`` satisfies it; tests inject a stub.
    """

    model_id: str

    def score_text(self, text: str) -> list[float]:  # bits per token
        ...


def perplexity_from_backend(backend: _ScorerBackend, text: str) -> float:
    """Perplexity of ``text`` under ``backend``.

    ``SurprisalBackend.score_text`` returns per-token surprisal in BITS
    (length len(tokens) - 1). Perplexity = 2 ** mean_bits = exp(mean_nats).
    An empty / single-token text yields an empty series → perplexity 0.0
    (the feature extractor's rank-0 guard then sets the ratio features to
    None). This is the ONLY function that touches the model; tests bypass it
    by injecting perplexities directly into ``score_window``.
    """
    series = backend.score_text(text)
    # SurprisalBackend.score_text may return a (series, top_k) tuple when
    # return_top_k > 0; we never pass that, so series is the bits list.
    if not series:
        return 0.0
    mean_bits = sum(series) / len(series)
    return 2.0 ** mean_bits


# =====================================================================
# Score orchestrator (the model-free M1 core)
# =====================================================================


def score_window(
    text: str,
    *,
    backend: _ScorerBackend | None = None,
    seed: int = DEFAULT_SEED,
    injected_perplexities: tuple[float, float, float] | None = None,
) -> dict[str, Any]:
    """Run the full shuffle + feature pipeline over one window.

    Two modes, both model-free at THIS layer:

      * ``injected_perplexities=(ppl_orig, ppl_sent, ppl_word)`` — the CI /
        stub path: features are computed from the injected triple; no backend
        is touched. The shuffles still run (so the shuffle functions are
        exercised), but their perplexities are supplied rather than scored.
      * ``backend`` real (or a stub exposing ``score_text``) — scores the
        original + the two shuffled variants via ``perplexity_from_backend``.

    Returns a dict carrying the perplexity triple, the seed, the model id,
    the score version, the 5 features, and any caveats. No threshold / band.
    """
    caveats: list[str] = []
    n_words = count_words(text)
    if n_words < MIN_STABLE_WORDS:
        caveats.append("target_too_short_for_stable_estimate")

    sentences = split_sentences(text)
    if len(sentences) < 2:
        # A single (or zero) sentence cannot be sentence-shuffled into a
        # different order; the sentence-shuffle degenerates to the original.
        # Surface it — the sentence-level features carry no information here.
        caveats.append("single_sentence_no_sentence_shuffle")
    sent_shuffled = shuffle_sentences(sentences, seed)
    word_shuffled = shuffle_words(text, seed)

    if injected_perplexities is not None:
        ppl_orig, ppl_sent, ppl_word = injected_perplexities
        model_id = backend.model_id if backend is not None else None
    else:
        if backend is None:
            raise ValueError(
                "score_window needs either a backend or injected_perplexities"
            )
        ppl_orig = perplexity_from_backend(backend, text)
        ppl_sent = perplexity_from_backend(backend, sent_shuffled)
        ppl_word = perplexity_from_backend(backend, word_shuffled)
        model_id = backend.model_id

    if ppl_orig <= 0.0:
        caveats.append("ppl_orig_degenerate_relative_features_unavailable")

    features = extract_shuffle_features(ppl_orig, ppl_sent, ppl_word)

    return {
        "model_id": model_id,
        "seed": seed,
        "ppl_orig": ppl_orig,
        "ppl_sent": ppl_sent,
        "ppl_word": ppl_word,
        "features": features,
        "score_version": SCORE_VERSION,
        "n_words": n_words,
        "n_sentences": len(sentences),
        "caveats": caveats,
    }


def audit(
    target_text: str,
    *,
    backend: _ScorerBackend | None = None,
    seed: int = DEFAULT_SEED,
    injected_perplexities: tuple[float, float, float] | None = None,
) -> dict[str, Any]:
    """Run the audit and return the ``results`` dict (pre-envelope).

    ``injected_perplexities`` is the stub/test injection point so no model
    loads in CI. Production callers pass a real ``backend`` and no injection.
    """
    results = score_window(
        target_text,
        backend=backend,
        seed=seed,
        injected_perplexities=injected_perplexities,
    )
    # The uncalibrated posture is surfaced explicitly so a consumer knows the
    # absence of a band is intentional, not a bug.
    results["caveats"].append("no_calibrated_thresholds_supplied")
    return results


def compose_envelope(
    *,
    target_path: Path | None,
    target_words: int,
    results: dict[str, Any],
    licenses_text: str = DEFAULT_LICENSES,
    does_not_license_text: str = DEFAULT_DOES_NOT_LICENSE,
) -> dict[str, Any]:
    caveats = list(results.get("caveats", []))

    license_block = ClaimLicense(
        task_surface=TASK_SURFACE,
        licenses=licenses_text,
        does_not_license=does_not_license_text,
        comparison_set={
            "scoring_model": results.get("model_id"),
            "score_version": results.get("score_version"),
            "seed": results.get("seed"),
            "threshold": None,
        },
        additional_caveats=caveats,
        references=[
            "Luminol-AIDetect, arXiv:2604.25860 (2026) "
            "[PROVISIONAL — UNVERIFIED preprint; M0 confirmation gates M2]",
            "Mitchell et al. 2023, 'DetectGPT: Zero-Shot Machine-Generated "
            "Text Detection using Probability Curvature' (arXiv:2301.11305) "
            "— the perturbation-based detection paradigm this order-shuffle "
            "probe extends (prior-art fallback if 2604.25860 is unconfirmed).",
        ],
    )

    return build_output(
        task_surface=TASK_SURFACE,
        tool=TOOL_NAME,
        version=SCRIPT_VERSION,
        target_path=target_path,
        target_words=target_words,
        baseline=None,
        results=results,
        claim_license=license_block,
        available=True,
        warnings=caveats,
    )


def render_markdown(envelope: dict[str, Any]) -> str:
    results = envelope["results"]
    target = envelope["target"]
    feats = results.get("features", {})

    def _fmt(v: Any) -> str:
        return f"{v:.4f}" if isinstance(v, (int, float)) else "(unavailable)"

    lines: list[str] = []
    lines.append("# Structural-Shuffle Perplexity Audit")
    lines.append("")
    lines.append(
        f"- **Target:** `{target.get('path')}` ({target.get('words')} words)"
    )
    lines.append(f"- **Scoring model:** `{results.get('model_id')}`")
    lines.append(f"- **Score version:** `{results.get('score_version')}`")
    lines.append(f"- **Seed:** {results.get('seed')}")
    lines.append("")

    lines.append("## Perplexities")
    lines.append("")
    lines.append(f"- **ppl_orig:** {_fmt(results.get('ppl_orig'))}")
    lines.append(f"- **ppl_sent (sentence-shuffled):** {_fmt(results.get('ppl_sent'))}")
    lines.append(f"- **ppl_word (word-shuffled):** {_fmt(results.get('ppl_word'))}")
    lines.append("")

    lines.append("## Shuffle features")
    lines.append("")
    for key in ("ppl_sum", "ppl_diff", "ppl_ratio", "ppl_log_ratio", "ppl_pct_change"):
        lines.append(f"- **{key}:** {_fmt(feats.get(key))}")
    lines.append("")
    lines.append(
        "Higher ppl_diff / ppl_ratio / ppl_log_ratio / ppl_pct_change = a "
        "larger perplexity jump under shuffling = more order-dependent = more "
        "human-like (hypothesis direction). **Not a verdict.**"
    )
    lines.append("**Verdict band:** none — ships uncalibrated, no threshold.")
    lines.append("")

    caveats = results.get("caveats") or []
    lines.append("## Caveats")
    lines.append("")
    if caveats:
        for c in caveats:
            lines.append(f"- {c}")
    else:
        lines.append("(none surfaced)")
    lines.append("")

    lines.append("## Claim license")
    lines.append("")
    lines.append(envelope["claim_license_rendered"].rstrip())
    lines.append("")

    lines.append("## Provenance")
    lines.append("")
    lines.append(f"- **Tool:** `{TOOL_NAME}` v{SCRIPT_VERSION}")
    lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Structural-shuffle perplexity audit — perplexity shift under "
            "sentence/word shuffling (Surface-5 discrimination evidence)."
        )
    )
    parser.add_argument("target", help="Path to target text file (UTF-8).")
    parser.add_argument(
        "--scorer", default=DEFAULT_SCORER,
        help=(
            "Scorer model alias or HF id (default "
            f"{DEFAULT_SCORER}). NOTE: gpt_neo_2_7b is the M2 scorer and is "
            "added to MODEL_ALIASES only behind the CPU-first verification "
            "gate; on a checkout without it, pass an on-rig alias (e.g. "
            "gpt2_medium) or a full HF id."
        ),
    )
    parser.add_argument(
        "--seed", type=int, default=DEFAULT_SEED,
        help=f"Seed for the (deterministic) shuffles (default {DEFAULT_SEED}).",
    )
    parser.add_argument(
        "--surprisal-dtype",
        choices=("auto", "fp32", "fp16", "bf16"),
        default="auto",
        help="Precision for the model load (default auto; bf16 on ROCm).",
    )
    parser.add_argument(
        "--device", default=None,
        help="Explicit torch device (cuda / cuda:1 / cpu). Default: auto.",
    )
    parser.add_argument(
        "--json", action="store_true",
        help="Print the JSON envelope to stdout instead of writing files.",
    )
    parser.add_argument(
        "--out", default=None,
        help="Evidence pack JSON path (default <target>.structural_shuffle.json).",
    )
    parser.add_argument(
        "--out-md", default=None,
        help="Evidence pack markdown path (default <target>.structural_shuffle.md).",
    )
    parser.add_argument("--licenses", default=DEFAULT_LICENSES)
    parser.add_argument("--does-not-license", default=DEFAULT_DOES_NOT_LICENSE)
    args = parser.parse_args(argv)

    target_path = Path(args.target)
    if not target_path.exists():
        print(f"error: target file not found at {target_path}", file=sys.stderr)
        return 1

    try:
        target_text = target_path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
        print(f"error: target not valid UTF-8: {exc}", file=sys.stderr)
        return 1

    target_words = count_words(target_text)

    # Fail cleanly when torch (the surprisal tier) is absent — a
    # dependency_check-style install hint, no traceback. We probe before
    # constructing the backend so the message names the missing tier. M1 is
    # model-free but the CLI scoring path is the M2 model seam, so the real
    # run needs the surprisal tier; tests inject perplexities and never hit
    # this path. (Mirrors fast_detect_curvature.)
    try:
        import torch  # type: ignore  # noqa: F401
    except ImportError:
        print(
            "error: structural-shuffle scoring needs the surprisal tier "
            "(transformers + torch), which is not installed.\n"
            "  Install with: pip install -r requirements-surprisal.txt\n"
            "  (opt-in Tier-4 / surprisal dependency layer; see "
            "scripts/calibration/RUNBOOK_tier4_install.md for the wheel "
            "decision tree and a smoke test).",
            file=sys.stderr,
        )
        return 2

    # Defer the backend import until after the torch gate so the install hint
    # fires cleanly rather than surfacing a deep ImportError.
    try:
        from surprisal_backend import (  # type: ignore
            SurprisalBackend,
            SurprisalBackendError,
            resolve_model_arg,
        )
    except ImportError as exc:  # pragma: no cover - exercised only on broken env
        print(f"error: surprisal backend unavailable: {exc}", file=sys.stderr)
        return 2

    try:
        backend = SurprisalBackend(
            model_id=resolve_model_arg(args.scorer),
            dtype=args.surprisal_dtype,
            device=args.device,
        )
    except SurprisalBackendError as exc:
        print(
            f"error: backend construction failed ({args.scorer}): {exc}",
            file=sys.stderr,
        )
        return 3

    try:
        results = audit(target_text, backend=backend, seed=args.seed)
    except SurprisalBackendError as exc:
        print(f"error: scoring failed ({args.scorer}): {exc}", file=sys.stderr)
        return 3

    envelope = compose_envelope(
        target_path=target_path,
        target_words=target_words,
        results=results,
        licenses_text=args.licenses,
        does_not_license_text=args.does_not_license,
    )

    if args.json:
        print(json.dumps(envelope, indent=2, default=str))
        return 0

    markdown = render_markdown(envelope)
    out_json = (
        Path(args.out)
        if args.out
        else target_path.with_suffix(target_path.suffix + ".structural_shuffle.json")
    )
    out_md = (
        Path(args.out_md)
        if args.out_md
        else target_path.with_suffix(target_path.suffix + ".structural_shuffle.md")
    )
    out_json.write_text(
        json.dumps(envelope, indent=2, default=str), encoding="utf-8",
    )
    out_md.write_text(markdown, encoding="utf-8")
    print(f"Wrote {out_json} + {out_md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
