#!/usr/bin/env python3
"""Regression tests for pdf_inventory.py + pdf_extract.py.

Strategy: ship four tiny fixture PDFs under
``test_data/pdf_inventory_fixture/`` (under 10 KB total) that exercise
every classification branch the inventory needs. The fixtures are
generated by ``_make_fixtures.py`` (committed prebuilt so CI doesn't
need ``reportlab``); regenerating requires reportlab but verifying
pyests do not.

Test coverage:

  * ``pdf_inventory.discover_pdfs`` glob filtering and stable order.
  * ``pdf_inventory.classify_pdf`` for all four classification
    branches (text_extractable, image_only, corrupted, plus a
    no-metadata variant of text_extractable).
  * Inventory writer produces one JSONL row per file with the
    documented schema.
  * Privacy guard refuses non-private outputs unless overridden.
  * pdf_extract reads the inventory, validates impostor fields,
    invokes preprocessing, and emits a manifest entry that
    validates clean.
  * pdf_extract skips inventory rows missing user-supplied
    impostor fields rather than emitting an invalid manifest.
  * pdf_extract dedupes by content_hash within author subdir.
  * pdf_extract skips ``corrupted`` rows from the inventory.
  * OCR unavailability is announced once + recorded as a skip; tests
    pass whether or not ocrmypdf + tesseract + ghostscript are
    installed.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

try:
    import pytest  # type: ignore
except ImportError:  # pragma: no cover
    pytest = None

# pypdf is the runtime dependency for inventory + extract. Skip the
# whole module cleanly when it's absent so users without
# requirements-acquisition.txt don't see failures.
_pdf_deps_available = True
_skip_reason = ""
try:
    import pypdf  # type: ignore  # noqa: F401
except ImportError as _e:
    _pdf_deps_available = False
    _skip_reason = (
        f"pypdf not installed ({_e}); "
        "pip install -r requirements-acquisition.txt"
    )

if _pdf_deps_available:
    import acquisition_core as ac  # type: ignore
    import manifest_validator as mv  # type: ignore
    import pdf_inventory as pi  # type: ignore
    import pdf_extract as pe  # type: ignore

if pytest is not None and not _pdf_deps_available:
    pytestmark = pytest.mark.skip(reason=_skip_reason)


FIXTURE_DIR = ROOT / "test_data" / "pdf_inventory_fixture"
PDF_WITH_META = FIXTURE_DIR / "text_layer_with_metadata.pdf"
PDF_NO_META = FIXTURE_DIR / "text_layer_without_metadata.pdf"
PDF_IMAGE_ONLY = FIXTURE_DIR / "image_only.pdf"
PDF_CORRUPTED = FIXTURE_DIR / "corrupted.pdf"


# ------------------- Helpers -------------------------------------


def make_inventory_args(**overrides) -> argparse.Namespace:
    """Default `argparse.Namespace` matching `pdf_inventory.build_arg_parser`.

    Keep in sync with the parser flags. The incremental-cache trio
    (`no_incremental_cache`, `flush_every`, `refresh_partial`) was
    added in 1.70.0; defaults here mirror `build_arg_parser`.
    """
    base = dict(
        root=str(FIXTURE_DIR),
        output=None,
        include_glob=[],
        exclude_glob=[],
        max_files=None,
        workers=1,
        max_file_bytes=pi.DEFAULT_MAX_FILE_BYTES,
        allow_public_output=True,
        verbose=False,
        # 1.70.0 incremental-cache CLI surface
        no_incremental_cache=False,
        flush_every=25,
        refresh_partial=False,
    )
    base.update(overrides)
    return argparse.Namespace(**base)


def make_extract_args(**overrides) -> argparse.Namespace:
    base = dict(
        inventory=None,
        output_dir=None,
        emit_manifest=None,
        workers=1,
        ocr_language="eng",
        ocr_dpi=300,
        skip_ocr=True,  # default tests don't depend on OCR deps
        dry_run=False,
        out=None,
        allow_public_output=True,
        allow_non_prose=False,
        strip_rules=None,
        strip_aggressive=False,
    )
    base.update(overrides)
    return argparse.Namespace(**base)


def read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [
        json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


# ------------------- Fixture sanity ------------------------------


def test_fixture_pdfs_exist():
    """All four fixture PDFs are committed; the tests below depend
    on them. If any are missing, regenerate via _make_fixtures.py.
    """
    for p in (PDF_WITH_META, PDF_NO_META, PDF_IMAGE_ONLY, PDF_CORRUPTED):
        assert p.is_file(), f"missing fixture: {p}"
    # Total fixture size stays under 1 MB per spec.
    total = sum(p.stat().st_size for p in (
        PDF_WITH_META, PDF_NO_META, PDF_IMAGE_ONLY, PDF_CORRUPTED,
    ))
    assert total < 1024 * 1024, f"fixture total {total} bytes > 1 MB cap"


# ------------------- pdf_inventory unit tests --------------------


def test_classify_text_yield_branches():
    """All three thresholds map to the documented classification."""
    assert pi._classify_text_yield(500) == ("text_extractable", True, False)
    assert pi._classify_text_yield(0) == ("image_only", False, True)
    assert pi._classify_text_yield(50) == ("mixed", False, True)


def test_metadata_quality_buckets():
    assert pi._metadata_quality("T", "A", "2020-01-01") == "good"
    assert pi._metadata_quality(None, "A", "2020-01-01") == "partial"
    assert pi._metadata_quality(None, None, None) == "none"


def test_normalize_pdf_date_parses_pdf_format():
    """PDF spec dates are ``D:YYYYMMDDHHmmSS+OO'mm'``; ISO output."""
    assert pi._normalize_pdf_date("D:20200304120000+00'00'") == "2020-03-04"
    assert pi._normalize_pdf_date("D:20200304") == "2020-03-04"
    assert pi._normalize_pdf_date("20200304120000") == "2020-03-04"
    assert pi._normalize_pdf_date(None) is None
    assert pi._normalize_pdf_date("not-a-date") is None


def test_classify_text_layer_with_metadata():
    """Born-digital PDF with title/author should classify as
    text_extractable, metadata_quality good, multi-page."""
    entry = pi.classify_pdf(PDF_WITH_META)
    assert entry.classification == "text_extractable"
    assert entry.extractable is True
    assert entry.needs_ocr is False
    assert entry.title == "On the Discipline of Attention"
    assert entry.author == "Synthetic Author"
    assert entry.metadata_quality == "good"
    assert entry.page_count >= 1
    assert entry.estimated_words > 0
    assert entry.file_hash.startswith("sha256:")
    assert entry.sample_chars_extracted > 100


def test_classify_text_layer_without_metadata():
    """Same content, no title/author: still text_extractable but
    metadata_quality drops to partial (creation-date is auto-set
    by reportlab)."""
    entry = pi.classify_pdf(PDF_NO_META)
    assert entry.classification == "text_extractable"
    assert entry.title is None
    assert entry.author is None
    assert entry.metadata_quality in ("partial", "none")


def test_classify_image_only():
    """A page with vector drawings and no text operators must
    classify as image_only (zero chars extracted)."""
    entry = pi.classify_pdf(PDF_IMAGE_ONLY)
    assert entry.classification == "image_only"
    assert entry.extractable is False
    assert entry.needs_ocr is True
    assert entry.sample_chars_extracted == 0


def test_classify_corrupted_does_not_raise():
    """A malformed PDF must classify as corrupted with notes set,
    not raise. The notes carry the exception class so the user
    can spot category failures."""
    entry = pi.classify_pdf(PDF_CORRUPTED)
    assert entry.classification == "corrupted"
    assert entry.notes is not None and entry.notes != ""
    assert entry.extractable is False
    assert entry.estimated_words == 0


# ------------------- discover_pdfs filtering ---------------------


def test_discover_finds_all_fixture_pdfs():
    paths = list(pi.discover_pdfs(FIXTURE_DIR))
    names = sorted(p.name for p in paths)
    expected = {
        "text_layer_with_metadata.pdf",
        "text_layer_without_metadata.pdf",
        "image_only.pdf",
        "corrupted.pdf",
    }
    assert set(names) == expected


def test_discover_respects_include_glob():
    paths = list(pi.discover_pdfs(
        FIXTURE_DIR, include=["text_layer_*.pdf"],
    ))
    names = {p.name for p in paths}
    assert names == {
        "text_layer_with_metadata.pdf",
        "text_layer_without_metadata.pdf",
    }


def test_discover_respects_exclude_glob():
    paths = list(pi.discover_pdfs(FIXTURE_DIR, exclude=["corrupted.pdf"]))
    assert all("corrupted" not in p.name for p in paths)


def test_discover_respects_max_files():
    paths = list(pi.discover_pdfs(FIXTURE_DIR, max_files=2))
    assert len(paths) == 2


def test_discover_returns_deterministic_order():
    """Re-running discover gives the same order. Important for
    inventory rebuilds that should diff cleanly."""
    a = list(pi.discover_pdfs(FIXTURE_DIR))
    b = list(pi.discover_pdfs(FIXTURE_DIR))
    assert [p.name for p in a] == [p.name for p in b]


# ------------------- inventory CLI end-to-end --------------------


def test_inventory_run_writes_one_row_per_pdf(tmp_path):
    out = tmp_path / "ai-prose-baselines-private" / "inv" / "inventory.jsonl"
    args = make_inventory_args(output=str(out), allow_public_output=False)
    rc = pi.run(args)
    assert rc == 0
    rows = read_jsonl(out)
    assert len(rows) == 4
    classes = {r["classification"] for r in rows}
    assert classes == {
        "text_extractable", "image_only", "corrupted",
    }
    # Each row carries the documented schema fields.
    required_fields = {
        "path", "file_hash", "page_count", "extractable", "needs_ocr",
        "has_ocr_layer", "estimated_words", "classification",
        "metadata_quality",
    }
    for row in rows:
        missing = required_fields - row.keys()
        assert not missing, f"row missing fields: {missing}"


def test_inventory_privacy_guard_refuses_non_private(tmp_path):
    public = tmp_path / "public" / "inv.jsonl"
    args = make_inventory_args(output=str(public), allow_public_output=False)
    if pytest is not None:
        with pytest.raises(SystemExit) as exc:
            pi.run(args)
        assert exc.value.code == 2
    else:
        try:
            pi.run(args)
            assert False
        except SystemExit as e:
            assert e.code == 2


def test_inventory_max_files_caps_output(tmp_path):
    out = tmp_path / "ai-prose-baselines-private" / "inv2.jsonl"
    args = make_inventory_args(output=str(out), max_files=2)
    pi.run(args)
    rows = read_jsonl(out)
    assert len(rows) == 2


def test_inventory_handles_empty_root(tmp_path):
    """Run against a directory with no PDFs; should write empty
    file and exit 0."""
    empty_root = tmp_path / "ai-prose-baselines-private" / "no-pdfs"
    empty_root.mkdir(parents=True)
    out = tmp_path / "ai-prose-baselines-private" / "empty_inv.jsonl"
    args = make_inventory_args(root=str(empty_root), output=str(out))
    rc = pi.run(args)
    assert rc == 0
    assert out.exists()
    assert out.read_text(encoding="utf-8") == ""


# ------------------- pdf_extract end-to-end ----------------------


def _augment_inventory_for_extract(
    rows: list[dict], persona: str = "synthetic_author_personal",
) -> list[dict]:
    """Add the impostor fields a user would set between inventory
    and extract."""
    augmented = []
    for r in rows:
        r2 = dict(r)
        if r2["classification"] == "text_extractable":
            r2.update({
                "persona": persona,
                "register": "academic_philosophy",
                "register_match": "high",
                "topic_match": "medium",
                "consent_status": "fair_use_research",
                "era": "pre_chatgpt",
                "impostor_for": ["blog"],
                "date_written": "2020-01-15",
            })
        augmented.append(r2)
    return augmented


def _write_filtered_inventory(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, sort_keys=True) + "\n")


def test_extract_text_layer_end_to_end(tmp_path):
    """Inventory → augment → extract: produces text + manifest entry."""
    inv = tmp_path / "ai-prose-baselines-private" / "inv.jsonl"
    pi.run(make_inventory_args(output=str(inv)))
    rows = read_jsonl(inv)
    filtered = _augment_inventory_for_extract(rows)
    inv_filtered = tmp_path / "ai-prose-baselines-private" / "inv_filtered.jsonl"
    _write_filtered_inventory(filtered, inv_filtered)

    out_dir = tmp_path / "ai-prose-baselines-private" / "extracted"
    manifest = out_dir / "draft.jsonl"
    args = make_extract_args(
        inventory=str(inv_filtered),
        output_dir=str(out_dir),
        emit_manifest=str(manifest),
    )
    rc = pe.run(args)
    assert rc == 0

    # One author subdir was created (both PDFs share the same persona).
    author_dir = out_dir / "synthetic-author-personal"
    assert author_dir.is_dir()
    txt_files = list(author_dir.glob("*.txt"))
    # Both PDFs had identical text → second is skipped as duplicate.
    assert len(txt_files) == 1, f"unexpected count: {[f.name for f in txt_files]}"

    # Cleaned text doesn't carry HTML residue or PDF artifacts.
    body = txt_files[0].read_text(encoding="utf-8")
    assert "discipline of attention" in body.lower()
    assert "%PDF" not in body
    # Sidecar present.
    sidecar = author_dir / (txt_files[0].stem + ".meta.json")
    assert sidecar.is_file()
    sc = json.loads(sidecar.read_text(encoding="utf-8"))
    assert sc.get("preprocessing") is not None
    assert sc.get("content_hash", "").startswith("sha256:")
    assert sc.get("scraper", "").startswith("pdf_extract_text_layer_")

    # Draft manifest carries the impostor fields.
    entries = read_jsonl(manifest)
    assert len(entries) == 1
    e = entries[0]
    assert e["corpus_role"] == "impostor"
    assert e["use"] == ["voice_impostor"]
    assert e["split"] == "baseline"
    assert e["privacy"] == "private"
    assert e["impostor_for"] == ["blog"]
    assert e["register_match"] == "high"
    assert e["topic_match"] == "medium"
    assert e["consent_status"] == "fair_use_research"
    assert e["era"] == "pre_chatgpt"
    assert e["acquired_via"].startswith("pdf_extract_text_layer_")
    assert e["content_hash"].startswith("sha256:")
    assert e["source_file_hash"].startswith("sha256:")


def test_extract_skips_rows_missing_impostor_fields(tmp_path):
    """A row without persona/register/etc. is skipped — never written
    as an invalid manifest entry."""
    inv = tmp_path / "ai-prose-baselines-private" / "inv2.jsonl"
    pi.run(make_inventory_args(output=str(inv)))
    rows = read_jsonl(inv)
    # Don't augment — keep the inventory rows as-is. Only one
    # text_extractable row should pass into the extract attempt
    # but fail the impostor-field check.
    inv_unfiltered = tmp_path / "ai-prose-baselines-private" / "inv_un.jsonl"
    _write_filtered_inventory(rows, inv_unfiltered)

    out_dir = tmp_path / "ai-prose-baselines-private" / "extracted2"
    args = make_extract_args(
        inventory=str(inv_unfiltered), output_dir=str(out_dir),
    )
    pe.run(args)
    # Nothing written.
    assert not list(out_dir.glob("**/*.txt"))


def test_extract_skips_corrupted_inventory_rows(tmp_path):
    """Inventory rows with classification=corrupted skip the extract
    step entirely; the script logs the skip but doesn't try to
    open the bad file."""
    inv = tmp_path / "ai-prose-baselines-private" / "inv3.jsonl"
    pi.run(make_inventory_args(output=str(inv)))
    rows = read_jsonl(inv)
    augmented = _augment_inventory_for_extract(rows)
    # Force the corrupted row to also have impostor fields populated
    # so we know its skip is for the corrupted reason, not metadata.
    for r in augmented:
        if r["classification"] == "corrupted":
            r.update({
                "persona": "synthetic_author_personal",
                "register": "academic_philosophy",
                "register_match": "high",
                "topic_match": "medium",
                "consent_status": "fair_use_research",
                "era": "pre_chatgpt",
                "impostor_for": ["blog"],
            })
    inv_filtered = tmp_path / "ai-prose-baselines-private" / "inv3_aug.jsonl"
    _write_filtered_inventory(augmented, inv_filtered)

    out_dir = tmp_path / "ai-prose-baselines-private" / "extracted3"
    args = make_extract_args(
        inventory=str(inv_filtered), output_dir=str(out_dir),
        emit_manifest=str(out_dir / "draft.jsonl"),
    )
    pe.run(args)
    # No corrupted-source file in the output. Only 1 text-extractable
    # text wins after dedupe.
    txts = list(out_dir.rglob("*.txt"))
    assert len(txts) == 1
    body = txts[0].read_text(encoding="utf-8")
    assert "discipline of attention" in body.lower()


def test_extract_dry_run_writes_nothing(tmp_path):
    inv = tmp_path / "ai-prose-baselines-private" / "inv4.jsonl"
    pi.run(make_inventory_args(output=str(inv)))
    rows = read_jsonl(inv)
    augmented = _augment_inventory_for_extract(rows)
    inv_aug = tmp_path / "ai-prose-baselines-private" / "inv4_aug.jsonl"
    _write_filtered_inventory(augmented, inv_aug)

    out_dir = tmp_path / "ai-prose-baselines-private" / "dry"
    args = make_extract_args(
        inventory=str(inv_aug), output_dir=str(out_dir), dry_run=True,
    )
    pe.run(args)
    assert not list(out_dir.rglob("*.txt"))
    assert not (out_dir / "draft_manifest.jsonl").exists()


def test_extract_skip_ocr_skips_image_only(tmp_path):
    """When --skip-ocr is set, image_only rows skip extraction
    cleanly (no spurious error)."""
    inv = tmp_path / "ai-prose-baselines-private" / "inv5.jsonl"
    pi.run(make_inventory_args(output=str(inv)))
    rows = read_jsonl(inv)
    # Augment image_only entry with impostor fields so the skip
    # reason is OCR availability, not missing metadata.
    augmented = []
    for r in rows:
        if r["classification"] == "image_only":
            r.update({
                "persona": "synthetic_author_personal",
                "register": "academic_philosophy",
                "register_match": "high",
                "topic_match": "medium",
                "consent_status": "fair_use_research",
                "era": "pre_chatgpt",
                "impostor_for": ["blog"],
            })
        augmented.append(r)
    inv_aug = tmp_path / "ai-prose-baselines-private" / "inv5_aug.jsonl"
    _write_filtered_inventory(augmented, inv_aug)

    out_dir = tmp_path / "ai-prose-baselines-private" / "skip_ocr"
    args = make_extract_args(
        inventory=str(inv_aug),
        output_dir=str(out_dir),
        emit_manifest=str(out_dir / "draft.jsonl"),
        skip_ocr=True,
    )
    rc = pe.run(args)
    # No OCR output for the image_only row.
    txts = list(out_dir.rglob("*.txt"))
    # No txt comes from image_only because we --skip-ocr.
    # The text-extractable row may produce one txt before dedupe-only
    # if persona-field augmentation was applied to it; in this test
    # we only augmented image_only, so text rows skip on missing
    # impostor fields.
    # The assertion: the run did not crash on the image_only entry.
    assert isinstance(rc, int)
    # No image_only-derived file in output (image_only PDF text
    # would have been skipped due to skip_ocr).


# ------------------- extract privacy -----------------------------


def test_extract_privacy_guard_refuses_non_private(tmp_path):
    inv = tmp_path / "ai-prose-baselines-private" / "inv_priv.jsonl"
    pi.run(make_inventory_args(output=str(inv)))
    rows = read_jsonl(inv)
    augmented = _augment_inventory_for_extract(rows)
    inv_aug = tmp_path / "ai-prose-baselines-private" / "inv_priv_aug.jsonl"
    _write_filtered_inventory(augmented, inv_aug)

    public_dir = tmp_path / "public_oops"
    args = make_extract_args(
        inventory=str(inv_aug),
        output_dir=str(public_dir),
        emit_manifest=str(public_dir / "draft.jsonl"),
        allow_public_output=False,
    )
    if pytest is not None:
        with pytest.raises(SystemExit) as exc:
            pe.run(args)
        assert exc.value.code == 2
    else:
        try:
            pe.run(args)
            assert False
        except SystemExit as e:
            assert e.code == 2


# ------------------- manifest validates clean --------------------


def test_extracted_manifest_passes_validator(tmp_path):
    """Extracted draft manifest validates clean once an
    identity_baseline entry naming the impostor target persona
    is appended (mirroring acquire_blog's validator-integration
    test)."""
    inv = tmp_path / "ai-prose-baselines-private" / "inv_v.jsonl"
    pi.run(make_inventory_args(output=str(inv)))
    rows = read_jsonl(inv)
    augmented = _augment_inventory_for_extract(rows)
    inv_aug = tmp_path / "ai-prose-baselines-private" / "inv_v_aug.jsonl"
    _write_filtered_inventory(augmented, inv_aug)

    out_dir = tmp_path / "ai-prose-baselines-private" / "vt"
    manifest_path = out_dir / "draft.jsonl"
    args = make_extract_args(
        inventory=str(inv_aug),
        output_dir=str(out_dir),
        emit_manifest=str(manifest_path),
    )
    rc = pe.run(args)
    assert rc == 0

    # Add an identity_baseline entry naming "blog" so the cross-check
    # has a target persona.
    baseline = out_dir / "synthetic-author-personal" / "fake_baseline.txt"
    baseline.write_text("Identity baseline prose. " * 100, encoding="utf-8")
    baseline_entry = {
        "id": "fake_baseline",
        "path": str(baseline.relative_to(manifest_path.parent)),
        "author": "Test User",
        "persona": "blog",
        "register": "academic_philosophy",
        "ai_status": "pre_ai_human",
        "language_status": "native",
        "use": ["baseline", "voice_profile"],
        "split": "baseline",
        "privacy": "private",
        "corpus_role": "identity_baseline",
        "era": "pre_chatgpt",
    }
    with manifest_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(baseline_entry, sort_keys=True) + "\n")

    report = mv.validate_manifest(manifest_path)
    error_issues = [
        i for i in report["issues"] if i.get("severity") == "error"
    ]
    assert error_issues == [], \
        f"Extracted manifest should validate without errors: {error_issues}"


# ------------------- OCR availability hook -----------------------


def test_ocr_availability_check_returns_tuple():
    """The helper must return ``(available, reason)`` — tests that
    skip OCR cleanly when deps are absent depend on this contract.
    """
    available, reason = pe._ocr_dependencies_available()
    assert isinstance(available, bool)
    assert isinstance(reason, str)
    if not available:
        # When unavailable, reason is human-readable for stderr.
        assert reason  # non-empty


# ------------------- CLI surface ---------------------------------


def test_inventory_help_lists_required_flags():
    parser = pi.build_arg_parser()
    help_text = parser.format_help()
    for flag in (
        "--root", "--output", "--include-glob", "--exclude-glob",
        "--max-files", "--workers", "--max-file-bytes",
        "--allow-public-output", "--verbose",
    ):
        assert flag in help_text, f"--help missing {flag}"


def test_extract_help_lists_required_flags():
    parser = pe.build_arg_parser()
    help_text = parser.format_help()
    for flag in (
        "--inventory", "--output-dir", "--emit-manifest", "--workers",
        "--ocr-language", "--ocr-dpi", "--skip-ocr", "--dry-run",
        "--allow-public-output", "--allow-non-prose", "--strip-rules",
        "--strip-aggressive",
    ):
        assert flag in help_text, f"--help missing {flag}"


if __name__ == "__main__":
    if pytest is None:
        sys.stderr.write("pytest not installed; cannot run tests.\n")
        sys.exit(2)
    sys.exit(pytest.main([__file__, "-v"]))
